#!/usr/bin/env bash
source "${0%/*}/__common__"

if [[ $# -lt 4 ]]; then
  echo "usage: cpprun <compiler> <usage_msg> <std_version> <filepath>"
  return
fi

compiler="$1"; shift
usage_msg="$1"; shift
stdver="$1"; shift
filepath=$(realpath "$1"); shift

if [[ ! -f "$filepath" ]]; then
  echo $usage_msg
  echo "\n- error: <filepath> was not found."
  return
fi

bin_path="/tmp/cpprun/"
mkdir -p $bin_path
bin_name=$(mktemp -u "$bin_path/XXXXXXXXXX")

"$compiler" --std="c++$stdver" $filepath -o $bin_name && "$bin_name"

if [[ -f "$bin_name" ]]; then
  rm "$bin_name"
fi
