#!/usr/bin/env bash
source "${0%/*}/__common__"source "${0%/*}/__common__"

sync() {
	pushd "${DOTFILES}"
	git status -s
	git stash > /dev/null
	git pull --quiet
	git stash pop > /dev/null
	git add -A
	git commit -m "Updates ($(date +%s))" > /dev/null
	git push --quiet
	popd  2> /dev/null || :
}

OPTIONS=( "Edit" "Sync" "Run" "VSCode" )
option=$(printf "%s\n" "${OPTIONS[@]}" | fzf_h "Choose an action")

[[ "${option}" == "Sync"   ]] && sync
[[ "${option}" == "Edit"   ]] && code "${DOTFILES}"
[[ "${option}" == "Run"    ]] && "${DOTFILES}/linux/install.sh" "$@"
[[ "${option}" == "VSCode" ]] && python "$DOTFILES/common/vscode/extensions.py" "$@"
