#!/usr/bin/env bash
source ".bash_common"

OPTIONS=(
  "WORK"
  "LIFE"
)
option=$(choose_one -p "Choose an action" -- "${OPTIONS[@]}")

log_info "Focus mode set to: ${option}"

op="rm"; suffix=""
[[ "${option}" == "WORK" ]] && { op="add"; suffix="::1" }

TO_BLOCK=(
  "youtube.com"
  "reddit.com"
  "x.com"
  "linkedin.com"
)
for domain in "${TO_BLOCK[@]}"; do
  sudo hostess "${op}" "${domain}" "${suffix}"
  sudo hostess "${op}" "www.${domain}" "${suffix}"
done
