#!/usr/bin/env bash
source ".dotfiles_common"
guard__is_git

local_delete_flag="-d"
[[ "$#" > 1 && "$1" == "-f" ]] && local_delete_flag="-D"

branch=$(git --no-pager branch | grep -P '^(?!.*(main|master|release))' | fzf_h "Choose one branch")
branch=$(echo "${branch}" | sed -E 's/^\*?[ ]*//; s/^\+?[ ]*//; s/[ ]*$//')

[[ -z "${branch}" ]] && { echo "-- No branch selected."; exit 1; }

read -k 1 -r "?@ Deleting local, sure? [y/N] "; echo
[[ $REPLY =~ ^[Yy]$ ]] && git branch $local_delete_flag $branch

read -k 1 -r "?@ Deleting remote, sure? [y/N] "; echo
[[ $REPLY =~ ^[Yy]$ ]] && git push origin --delete $branch
