#!/usr/bin/env bash
source ".bash_common"
guard__is_git

branch=$(git branch -a | fzf_h)

echo "${branch}" | \
sed -E 's/^remotes\/origin\///' | \
sed -E 's/^\*?[ ]*//' | \
sed -E 's/^\+?[ ]*//' | \
xargs git switch
