#!/usr/bin/env bash
set -eEu -o pipefail
shopt -s xpg_echo

branch=$(git branch -a | fzf_h "Choose one branch")

echo "$branch" | \
sed -E 's/^remotes\/origin\///' | \
sed -E 's/^\*?[ ]*//' | \
xargs git switch
