#!/usr/bin/env bash
source ".bash_common"


################################################################################
### Actions
################################################################################

is_file_or_dir() {
  [[ -f "${1}" ]] ||  [[ -d "${1}" ]] && return 0
  return 1
}

silent() {
  is_file_or_dir "${1}" && item="xdg-open ${1}" || item="${1}"
  eval "${item}" >/dev/null 2>&1 &
  exit 0
}
detached() {
  is_file_or_dir "${1}" && item="xdg-open ${1}" || item="${1}"
  eval "${item}" &
  exit 0
}
block() {
  is_file_or_dir "${1}" && item="xdg-open ${1}" || item="${1}"
  eval "${item}"
  exit 0
}


################################################################################
### Parse args
################################################################################

#! Help

usage() {
  echo "Usage: $(basename "${BASH_SOURCE[0]}") [options] [ITEM_TO_OPEN]"
  echo ""
  echo "Options:"
  echo "  -s | --silent     No log, no block"
  echo "  -d | --detached   Log, no block"
  echo "  -b | --block      Log and block"
  echo "  -h | --help       Show this message"
  echo "  --                Extra args after this"
  exit 1
}

#! Process options

while [[ "${#}" > 0 ]]; do
  case "${1}" in
    -s | --silent   ) shift; silent   "$@" ;;
    -d | --detached ) shift; detached "$@" ;;
    -b | --block    ) shift; block    "$@" ;;
    -h | --help     ) shift; usage ;;
    --              ) shift; break ;;
    *               ) break ;;
  esac
done


################################################################################
### Interactive
################################################################################

OPTIONS=( "Silent" "Detached" "Block" )
option=$(choose_one -p "How to open it?" -- "${OPTIONS[@]}")

[[ "${option}" == "Silent"   ]] && silent   "$@"
[[ "${option}" == "Detached" ]] && detached "$@"
[[ "${option}" == "Block"    ]] && block    "$@"
