#!/usr/bin/env bash
source "${0%/*}/__common__"

OPTIONS=( "Detached" "Silent" "Hold" )
option=$(printf "%s\n" "${OPTIONS[@]}" | fzf_h "Choose one mode")

[[ "${option}" == "Detached" ]] && xdg-open $1 &
[[ "${option}" == "Silent"   ]] && xdg-open $1 >/dev/null 2>&1 &
[[ "${option}" == "Hold"     ]] && xdg-open $1
