#!/usr/bin/env bash
source ".bash_common"


################################################################################
### Actions
################################################################################

silent() {
  xdg-open "$1" >/dev/null 2>/dev/null &
  exit 0
}
detached() {
  xdg-open "$1" &
  exit 0
}
block() {
  xdg-open "$1"
  exit 0
}


################################################################################
### Parse args
################################################################################

#! Help

usage() {
  echo "Usage: $(basename "${BASH_SOURCE[0]}") [options]"
  echo ""
  echo "Options:"
  echo "  -s | --silent     No log, no block"
  echo "  -d | --detached   Log, no block"
  echo "  -b | --block      Log and block"
  echo "  -h | --help       Show this message"
  echo "  --                Extra args after this"
  exit 1
}

#! Process options

while [[ "${#}" > 0 ]]; do
  case "${1}" in
    -s | --silent   ) shift; silent   "$@" ;;
    -d | --detached ) shift; detached "$@" ;;
    -b | --block    ) shift; block    "$@" ;;
    -h | --help     ) shift; usage ;;
    --              ) shift; break ;;
    *               ) break ;;
  esac
done


################################################################################
### Interactive
################################################################################

OPTIONS=( "Silent" "Detached" "Block" )
option=$(printf "%s\n" "${OPTIONS[@]}" | fzf_h)

[[ "${option}" == "Silent"   ]] && silent "$@"
[[ "${option}" == "Detached" ]] && detached "$@"
[[ "${option}" == "Block"    ]] && block "$@"
