#!/usr/bin/env bash
source ".dotfiles_common"

# Settings dir

settings_path="/tmp/user_ps"
mkdir -p "$settings_path"

# Threshold

threshold="${settings_path}/threshold"
[[ -f "$threshold" ]] || echo "1"   > "$threshold"
threshold_inc="t=\$(cat $threshold); echo \$((t+1)) > $threshold"
threshold_dec="t=\$(cat $threshold); [ \"\$t\" -gt 0 ] && echo \$((t-1)) > $threshold || echo \"\$t\" > $threshold"

# Sort Mode

sort_mode="${settings_path}/sort_mode"
[[ -f "${sort_mode}" ]] || echo "cpu" > "${sort_mode}"

# Preview

show_info="${settings_path}/show_info"
[[ -f "${show_info}" ]] || echo "0" > "${show_info}"
info_toggle="t=\$(cat ${show_info}); echo \$((1-t)) > ${show_info}"

info_size="10%"
[[ "$(tput cols)" < 130 ]] && info_size="30%"

info="down:${info_size}:wrap"
[[ "$(cat "${show_info}")" == "0" ]] && info="${info}:hidden"


# Render command

render='
    TH=$(cat "'$threshold'")
    MODE=$(cat "'${sort_mode}'")
    SORT_FLAG="--sort=-%${MODE}"

    ps -u '$USER' -o pid,ppid,%cpu,%mem,time,command $SORT_FLAG | \
    awk -v th="$TH" "NR==1 || \$3 >= th/10 || \$4 >= th/10 {
        n=split(\$6,a,\"/\");
        print \$1, \$2, \$3, \$4, \$5, a[n];
    }" | column -t
'

# "Loop"

eval "${render}" | SHELL=/bin/sh fzf \
    --header-lines=1 \
    --layout=reverse \
    --prompt="Process Manager > " \
    --border-label=$' ALT+  (k/K) Kill [Parent]  (+/-) Threshold  (c/m) Sort  (r) Reload  (i) Info ' \
    --border \
    --header-lines-border \
    --no-separator \
    --info=inline-right \
    --cycle \
    --bind "enter:become(echo {1})" \
    --bind "alt-enter:become(echo {2})" \
    --bind "alt-k:execute(kill -9 {1})+reload(${render})" \
    --bind "alt-K:execute(kill -9 {2})+reload(${render})" \
    --bind "alt-c:execute(echo 'cpu' > ${sort_mode})+reload(${render})" \
    --bind "alt-m:execute(echo 'mem' > ${sort_mode})+reload(${render})" \
    --bind "alt-+:execute($threshold_inc)+reload(${render})" \
    --bind "alt--:execute($threshold_dec)+reload(${render})" \
    --bind "alt-r:reload(${render})" \
    --bind "alt-i:execute(${info_toggle})+toggle-preview" \
    --preview "ps -ww -p {1} -o command=" \
    --preview-window="${info}"
