#!/usr/bin/env bash
source ".bash_common"

################################################################################
### Required
################################################################################

required_cmd "ydotool"


################################################################################
### Keycodes  (check: /usr/include/linux/input-event-codes.h)
################################################################################

CTRL=29
SHIFT=42
SUPER=125
UP=103
DOWN=108
LEFT=105
RIGHT=106
KEY_0=11
KEY_1=2
KEY_M=50
KEY_O=24
KEY_R=19
KEY_Q=16


################################################################################
### Vars
################################################################################

count_fullscreen=0
sleep_after_launch=0.5

################################################################################
### Utils
################################################################################

hold() {
  for key in "${@}"; do
    ydotool key "${key}:1"
  done
}
release() {
  for key in "${@}"; do
    ydotool key "${key}:0"
  done
}
press() {
  hold ${@}
  release ${@}
}
press_times() {
  key="${1}"; shift
  n="${1}"; shift
  for ((i = 0 ; i < ${n} ; i++ )); do
    press ${key}
  done
}

move() {
  press ${SUPER} ${SHIFT} ${1}
}
focus() {
  press ${SUPER} ${1}
}
rotate_layout() {
  press ${SUPER} ${KEY_O}
}

window_close() {
  press ${SUPER} ${KEY_Q}
}
window_maximize() {
  press ${SUPER} ${KEY_M}
}

launch() {
  eval "${1}" >/dev/null 2>&1 &
  sleep ${sleep_after_launch}
}
launch_in_new_workspace() {
  launch "${1}"
  move ${KEY_0}
  count_fullscreen=$(( count_fullscreen + 1 ))
}

testtest() {
  echo "${1}"
}

################################################################################
### Execution
################################################################################


# Set socket path
export YDOTOOL_SOCKET="$HOME/.ydotool_socket"
if ! ydotool key 29:1 29:0 >/dev/null 2>&1; then
  sudo -b ydotoold --socket-path="${YDOTOOL_SOCKET}" --socket-own="$(id -u):$(id -g)" >/dev/null 2>&1
  [[ $? != 0 ]] && error_exit "ydotool found but, can't be initialized."
else
  log_header "Workspace are already initialized"
  printf "└── Launch again? [y/N] "; read -n1; echo
  [[ $REPLY =~ ^[Yy]$ ]] || exit 0
fi

# Dummy window because vscode re-scale is really slow
sleep_after_launch=0.2
launch "ghostty" 

# Grow the dummy window to the left
hold ${SUPER} ${KEY_R}
press_times ${LEFT} 44
release ${SUPER} ${KEY_R}

# Launch our editor...
sleep_after_launch=1.2
launch "code"

# Close the dummy window (so 'code' takes its space)
focus ${LEFT}
window_close
sleep 0.5

# Change focus to the left and open the browser,
# it is opened down, so move it up!
focus ${LEFT}
launch "zen-browser"
move ${UP}
sleep 0.5

# Increase browser window a bit in vertical
hold ${SUPER} ${KEY_R}
press_times ${DOWN} 20
release ${SUPER} ${KEY_R}

# Fullscreen apps in separated workspaces
sleep_after_launch=2
launch_in_new_workspace "qtcreator"
launch_in_new_workspace "cosmic-files"
launch_in_new_workspace "flatpak run com.slack.Slack"

# Maximize them backward
for ((i = 0 ; i < ${count_fullscreen} ; i++)); do
  sleep 0.5
  window_maximize
  focus ${UP}
done

echo ""
