#!/usr/bin/env bash
source ".bash_common"


################################################################################
### Actions
################################################################################

sync() {
    cd "${DOTFILES}"
    git status -s
    git stash > /dev/null
    git pull --quiet
    git stash pop > /dev/null
    git add -A
    git commit -m "Updates ($(date +%s))" > /dev/null
    git push --quiet
    cd -
    exit 0
}

edit() {
    "$EDITOR" "$DOTFILES"
    exit 0
}

installer() {
    "${DOTFILES}/linux/install.sh" "$@"
    exit 0
}

manage_vscode() {
    python "$DOTFILES/configs/vscode/extensions.py" "$@"
    exit 0
}


################################################################################
### Parse args
################################################################################

#! Help

usage() {
    echo "Usage: $(basename "${BASH_SOURCE[-1]}") [options]"
    echo ""
    echo "Options:"
    echo "  -e | --edit       Edit dotfiles"
    echo "  -s | --sync       Sync dotfiles"
    echo "  -i | --installer  Run dotfiles \"installer\""
    echo "  -h | --help       Show this message"
    echo "  --                Extra args after this"
    exit 1
}

#! Process options

while [[ "${#}" > 0 ]]; do
    case "${1}" in
        -e | --edit      ) shift; edit               ;;
        -s | --sync      ) shift; sync               ;;
        -i | --installer ) shift; installer     "$@" ;;
        -c | --code      ) shift; manage_vscode "$@" ;;
        -h | --help      ) shift; usage ;;
        --               ) shift; break ;;
        *                ) break;;
    esac
done


################################################################################
### Interactive
################################################################################

OPTIONS=( "Edit" "Sync" "Installer" "VSCode" )
option=$(choose_one -p "Choose an action" -- "${OPTIONS[@]}")

[[ "${option}" == "Edit"      ]] && edit
[[ "${option}" == "Sync"      ]] && sync
[[ "${option}" == "Installer" ]] && installer     "$@"
[[ "${option}" == "VSCode"    ]] && manage_vscode "$@"
