#!/usr/bin/env bash
export frg_script_dir="$(cd "$(dirname "${BASH_SOURCE[-1]}")" && pwd)"

source "$frg_script_dir/.bash_common"
export -f error_exit log_error _log

source "$frg_script_dir/frg_helpers/_frg_colors"

required_cmd rg
required_cmd python

pattern="$1"
export SHELL=$(which bash)


frg_preview() {
    # expected input = <path>@<line>@<col_start>@<col_end>@<new_line_count>
    [[ $# < 1 ]] && error_exit "Usage: frg_preview <info> <pattern>"

    local info="$1"
    [[ -z "$info" ]] && return
    shift
    IFS='@' read -r f l cs ce count <<< "$info"
    count="${count%$'\e[0m'}"

    local b=25
    local l1=$((l>b?l-b:1))
    local l2=$((l+b))

    bat --wrap auto --color always --style numbers --line-range $l1:$l2 \
        --highlight-line "$l:$((l+count-1))" "$f" \
    | rg --color=always --passthru \
         --colors 'match:bg:blue' \
         --colors 'match:fg:black' \
         --colors 'match:style:bold' \
         -U -i "$1"
}
export -f frg_preview


frg_get() {
    [[ $# < 1 ]] && error_exit "Usage: data_input <pattern>"

    local pattern="$1"

    rg --json -U -i -e "$pattern" 2>/dev/null \
    | python "$frg_script_dir/frg_helpers/_frg_parse_rg_json.py" \
    | sed -e "s|^\\(.*/\\)|$(printf '\033[%sm' "$ANSI_PATH_FG")\1$(printf '\033[%sm' "$ANSI_PATH_FG_DEFAULT")|" \
          -e "s|@[0-9]\\+@[0-9]\\+@[0-9]\\+@[0-9]\\+$|${ANSI_CONTENT_FG}&${ANSI_RESET}|"
}
export -f frg_get


frg_main() {
    local binds='tab:replace-query,ctrl-t:toggle-preview,alt-p:preview-up,alt-n:preview-down,alt-t:preview-top,change:reload:frg_get {q}'

    fzf --ansi --cycle --phony \
        --reverse --height=100% --no-separator --no-scrollbar --border=none \
        --prompt="" \
        --query="$pattern" \
        --info=inline-right \
        --bind="$binds" \
        --color="$FZF_COLORS" \
        --pointer=">" \
        --preview='frg_preview {} {q}' \
        --preview-window="right,border-bold"
}


frg_get "$pattern" | frg_main | sed -e $'s/\e\\[[0-9;]*m//g' -e 's/\([^@]*\)@\([0-9]*\)@.*/\1:\2/'
