#!/usr/bin/env bash
source ".bash_common"
guard__is_git

url=$(git remote -v | head -n 1 | awk '{print $2}')

if [[ "${url}" == *@* ]]; then
  ssh=$(echo "${url}" | awk -F'@' '{print $2}' | sed 's/:/\//')
  xdg-open "https://${ssh}"  >/dev/null 2>&1 &
else
  xdg-open "${url}"  >/dev/null 2>&1 &
fi
