#!/usr/bin/env bash
source ".bash_common"
guard__is_git


################################################################################
### Utils
################################################################################

_git_all_branches(){
    git branch -a --format='%(refname:short)'
}


################################################################################
### Parse args
################################################################################

#! Help

usage() {
    echo "Usage: $(basename "${BASH_SOURCE[-1]}") [options]"
    echo ""
    echo "Options:"
    echo "  -n            How many branches to show"
    echo "  -h | --help   Show this message"
    echo "  --            Extra args after this"
    exit 1
}

#! Defaults

count=99999

#! Process options

while [[ "${#}" > 0 ]]; do
    case "${1}" in
        -n          ) shift; count=${1}; shift ;;
        -h | --help ) shift; usage ;;
        --          ) shift; break ;;
        *           ) break ;;
    esac
done


################################################################################
### Execution
################################################################################

sorted_branches="$(_git_all_branches | grep -v '^origin/'; _git_all_branches | grep '^origin/')"

echo "${sorted_branches}"           | \
    grep -v '^origin$'              | \
    head -${count}                  | \
    choose_one -p "Choose a branch" | \
    sed -E 's/^remotes\/origin\///' | \
    xargs -r git switch
