#!/usr/bin/env bash
set -eEu -o pipefail
shopt -s xpg_echo

ACTIONS=(
    "GET"
    "SET POWERSAVE"
    "SET PERFORMANCE"
)
action=$(printf "%s\n" "${ACTIONS[@]}" | fzf_h "Choose one action")

GOVERNOR_PATH="/sys/devices/system/cpu/cpu*/cpufreq/scaling_governor"

if [[ "${action}" == "GET" ]]; then

    cat "$GOVERNOR_PATH"

elif [[ "${action}" == "SET POWERSAVE" ]]; then

    echo powersave | sudo tee "$GOVERNOR_PATH"

elif [[ "${action}" == "SET PERFORMANCE" ]]; then

    echo performance | sudo tee "$GOVERNOR_PATH"

fi
