#!/usr/bin/env bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[-1]}")" && pwd)"
export PATH="$script_dir:$PATH"
source "$script_dir/.bash_common"

required_cmd frg

f="/tmp/hx_fzf.result"
rm -f "$f"
frg > "$f"
