#!/usr/bin/env bash
export frg_script_dir="$(cd "$(dirname "${BASH_SOURCE[-1]}")" && pwd)"

source "$frg_script_dir/.bash_common"
export -f error_exit log_error _log

source "$frg_script_dir/frg_helpers/_frg_colors"

required_cmd rg
required_cmd bat

export SHELL=$(which bash)

INITIAL_QUERY="${*:-}"
export TEMP=$(mktemp -u)
trap 'rm -f "$TEMP"' EXIT

TRANSFORMER='
  rg_pat={q:1}
  fzf_pat={q:2..}

  if ! [[ -r "$TEMP" ]] || [[ $rg_pat != $(cat "$TEMP") ]]; then
    echo "$rg_pat" > "$TEMP"
    printf "reload:sleep 0.1; rg --column --line-number --no-heading --color=always --smart-case %q || true" "$rg_pat"
  fi
  echo "+search:$fzf_pat"
'

fzf --ansi --cycle --disabled --reverse --height=100% --no-separator --no-scrollbar \
    --border=none --prompt="" --info=inline-right --query "$INITIAL_QUERY" \
    --color "${FZF_COLORS},hl:-1:underline,hl+:-1:underline:reverse" \
    --pointer=">" --with-shell 'bash -c' \
    --bind "start,change:transform:$TRANSFORMER" \
    --delimiter : \
    --preview 'p={q}; bat --color=always {1} --highlight-line {2} | rg --color=always --passthru --colors match:bg:blue --colors match:fg:black --colors match:style:bold -U -i "${p%% *}"' \

    --preview-window 'right,border-bold' \
    --bind 'enter:become(vim {1} +{2})'
