format = """
$directory\
$time\
$git_branch$git_status\
$cmd_duration\
$docker_context\
$character\
"""

scan_timeout = 500
command_timeout = 60000

add_newline = true

[fill]
symbol = ' '

[character]
format = "\n$symbol "

[directory]
truncation_length = 2
truncate_to_repo = false
# truncation_symbol = "…/"

[time]
disabled = false
time_format = "%T"
# format = '[$time ]($style)'

[cmd_duration]
format = '[[· ](teal)$duration]($style)'
