format = """
$directory\
$time\
$git_branch$git_status\
$cmd_duration\
$character\
"""
# $docker_context\

# Settings
scan_timeout = 500
command_timeout = 60000

# Disable the blank line at the start of the prompt
add_newline = true

# Create a fake right_prompt
[fill]
symbol = ' '

# Configure the divisor character of the prompt
[character]
format = "\n$symbol "

[directory]
truncation_length = 0
truncate_to_repo = false
# truncation_symbol = "…/"

[time]
disabled = false
time_format = "%T"
# format = '[$time ]($style)'

[cmd_duration]
format = '[[· ](teal)$duration]($style)'
