[env]
TERM = "xterm-256color"

[window]
padding = { x = 12, y = 12 }
decorations = "none"
opacity = 0.9
blur = true

[scrolling]
history = 100000

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 12

[bell]
animation = "Ease"
duration = 500

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Underline", blinking = "Off" }

[mouse]
hide_when_typing = true

################################################################################
### THEME : Gruvbox Material Hard Dark
################################################################################

[colors.primary]
background = '#1d2021'
foreground = '#d4be98'

[colors.normal]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'

[colors.bright]
black   = '#32302f'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#d4be98'
