#!/usr/bin/env bash
source ".bash_common"

################################################################################
### Required
################################################################################

required_cmd "ydotool"


################################################################################
### Keycodes  (check: /usr/include/linux/input-event-codes.h)
################################################################################

CTRL=29
SHIFT=42
SUPER=125
UP=103
DOWN=108
LEFT=105
RIGHT=106
KEY_0=11
KEY_1=2
KEY_M=50
KEY_O=24
KEY_R=19
KEY_Q=16


################################################################################
### Vars
################################################################################

count_fullscreen=0


################################################################################
### Utils
################################################################################

hold() {
    for key in "${@}"; do
        ydotool key "${key}:1"
    done
}
release() {
    for key in "${@}"; do
        ydotool key "${key}:0"
    done
}
press() {
    sleep 0.25
    hold ${@}
    release ${@}
}
press_times() {
    key="${1}"; shift
    n="${1}"; shift
    for ((i = 0 ; i < ${n} ; i++ )); do
        hold ${key}
        release ${key}
    done
}

move() {
    press ${SUPER} ${SHIFT} ${1}
}
focus() {
    press ${SUPER} ${1}
}
rotate_layout() {
    press ${SUPER} ${KEY_O}
}

window_close() {
    press ${SUPER} ${KEY_Q}
}
window_maximize() {
    press ${SUPER} ${KEY_M}
}

launch() {
    eval "${1}" >/dev/null 2>&1 &
    sleep 2  # Safe time to init the window and get the focus
}
launch_in_new_workspace() {
    launch "${1}"
    move ${KEY_0}
    count_fullscreen=$(( count_fullscreen + 1 ))
}


################################################################################
### Parse args
################################################################################

#! Help

usage() {
    echo "Usage: $(basename "${BASH_SOURCE[-1]}") [options]"
    echo ""
    echo "Options:"
    echo "  -1            Init only frist workspace"
    echo "  -0            Init only fullscreen workspaces"
    echo "  -d            Decrypt job folder"
    echo "  -h | --help   Show this message"
    echo "  --            Extra args after this"
    exit 1
}

#! Defaults

init_all=true
init_ws_1=false
init_ws_0=false
ask_for_decrypt=true
decrypt=false

#! Process options

while [[ "${#}" > 0 ]]; do
    case "${1}" in
        -1          ) shift; init_ws_1=true; init_all=false ;;
        -0          ) shift; init_ws_0=true; init_all=false ;;
        -d          ) shift; decrypt=true; ask_for_decrypt=false ;;
        -h | --help ) shift; usage ;;
        --          ) shift; break ;;
        *           ) break ;;
    esac
done


################################################################################
### Execution
################################################################################


#! Decrypt

if ${ask_for_decrypt}; then
    log_header "Before lauching the workspaces"
    printf "└── Decrypt job dir? [y/N] "; read -n1; echo
    [[ $REPLY =~ ^[Yy]$ ]] && omi -u
elif ${decrypt}; then
    omi -u
fi


#! Init / Validate ydotool

export YDOTOOL_SOCKET="$HOME/.ydotool_socket"

if ! ydotool key 29:1 29:0 >/dev/null 2>&1; then
    sudo -b ydotoold                      \
        --socket-path="${YDOTOOL_SOCKET}" \
        --socket-own="$(id -u):$(id -g)"  \
        >/dev/null 2>&1
    [[ $? != 0 ]] && error_exit "ydotool found but, can't be initialized."
else
    log_header "Workspace are already initialized"
    printf "└── Launch again? [y/N] "; read -n1; echo
    [[ $REPLY =~ ^[Yy]$ ]] || exit 0
fi


#! Workspace 1

if ${init_all} || ${init_ws_1}; then

    #! Code

    launch "qtcreator"
    hold ${SUPER} ${KEY_R}
    press_times ${LEFT} 40
    release ${SUPER} ${KEY_R}

fi


#! Fullscreen Workspaces

if ${init_all} || ${init_ws_0}; then

    # Launch apps in separated workspaces
    launch_in_new_workspace "zen-browser"
    launch_in_new_workspace "flatpak run com.slack.Slack"
    launch_in_new_workspace "cosmic-files"
    launch_in_new_workspace "code"

    # Maximize them backward
    for ((i = 0 ; i < ${count_fullscreen} ; i++)); do
        window_maximize
        focus ${UP}
    done

fi

echo ""
