[env]
TERM = "xterm-256color"

[window]
# padding = { x = 24, y = 0 } # wayland
# dynamic_padding = true # wayland
padding = { x = 4, y = 4 } # x11
# opacity = 0.9
blur = true # wayland or macos

[scrolling]
history = 100000

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
# size = 12 # wayland
size = 6 # x11 (?)

[bell]
animation = "Ease"
duration = 500

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Underline", blinking = "Off" }

[colors] # Gruvbox Dark Hard  (https://github.com/alacritty/alacritty-theme/blob/master/themes/gruvbox_dark.toml)
draw_bold_text_with_bright_colors = true
[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'
[colors.normal]
black = '#282828'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'
[colors.bright]
black = '#928374'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'
