[env]
TERM = "xterm-256color"

[window]
padding = { x = 12, y = 12 }
# opacity = 0.6
# blur = true # wayland-kde or macos
decorations = "None"

[scrolling]
history = 100000

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 12

[bell]
animation = "Ease"
duration = 500

[cursor]
style = { shape = "Block", blinking = "Always" }
vi_mode_style = { shape = "Underline", blinking = "Off" }

# [general]
# import = [
#     "~/.config/alacritty/themes/themes/{theme}.toml"
# ]

# Gruvbox Dark Hard  (https://github.com/alacritty/alacritty-theme/blob/master/themes/gruvbox_dark.toml)
###############################################################################
# [colors]
# draw_bold_text_with_bright_colors = true
# [colors.primary]
# background = '#1d2021'
# foreground = '#ebdbb2'
# [colors.normal]
# black = '#282828'
# red = '#cc241d'
# green = '#98971a'
# yellow = '#d79921'
# blue = '#458588'
# magenta = '#b16286'
# cyan = '#689d6a'
# white = '#a89984'
# [colors.bright]
# black = '#928374'
# red = '#fb4934'
# green = '#b8bb26'
# yellow = '#fabd2f'
# blue = '#83a598'
# magenta = '#d3869b'
# cyan = '#8ec07c'
# white = '#ebdbb2'


# Catppuccin Latte (https://github.com/alacritty/alacritty-theme/blob/master/themes/catppuccin_latte.toml)
###############################################################################
[colors.primary]
background = '#EFF1F5' # base
foreground = '#4C4F69' # text
dim_foreground = '#4C4F69' # text
bright_foreground = '#4C4F69' # text
[colors.cursor]
text = '#EFF1F5' # base
cursor = '#DC8A78' # rosewater
[colors.vi_mode_cursor]
text = '#EFF1F5' # base
cursor = '#7287FD' # lavender
[colors.search.matches]
foreground = '#EFF1F5' # base
background = '#6C6F85' # subtext0
[colors.search.focused_match]
foreground = '#EFF1F5' # base
background = '#40A02B' # green
[colors.footer_bar]
foreground = '#EFF1F5' # base
background = '#6C6F85' # subtext0
[colors.hints.start]
foreground = '#EFF1F5' # base
background = '#DF8E1D' # yellow
[colors.hints.end]
foreground = '#EFF1F5' # base
background = '#6C6F85' # subtext0
[colors.selection]
text = '#EFF1F5' # base
background = '#DC8A78' # rosewater
[colors.normal]
black = '#5C5F77' # subtext1
red = '#D20F39' # red
green = '#40A02B' # green
yellow = '#DF8E1D' # yellow
blue = '#1E66F5' # blue
magenta = '#EA76CB' # pink
cyan = '#179299' # teal
white = '#ACB0BE' # surface2
[colors.bright]
black = '#6C6F85' # subtext0
red = '#D20F39' # red
green = '#40A02B' # green
yellow = '#DF8E1D' # yellow
blue = '#1E66F5' # blue
magenta = '#EA76CB' # pink
cyan = '#179299' # teal
white = '#BCC0CC' # surface1
[colors.dim]
black = '#5C5F77' # subtext1
red = '#D20F39' # red
green = '#40A02B' # green
yellow = '#DF8E1D' # yellow
blue = '#1E66F5' # blue
magenta = '#EA76CB' # pink
cyan = '#179299' # teal
white = '#ACB0BE' # surface2
