# Flatpaks to remove
com.mattjakeman.ExtensionManager
com.jeffser.Alpaca
com.jeffser.Alpaca.Plugins.Ollama
io.github.josephmawa.Bella
io.github.nokse22.Exhibit
io.github.brunofin.Cohesion
net.lutris.Lutris
