
# --- Shell & Terminal ---
fish
fisher
fish-autopair
starship
7zip
# alacritty
ghostty
mprocs-bin
navi
tmux
wl-clipboard
zoxide

# --- Shell Tools ---
ripgrep
ripgrep-all
bat
dua-cli
duf
dust
glances
hyperfine
kondo
less
plocate
pv
scooter-bin
tombi
unrar
unzip
which
zip
fd
fzf
eza
jq
tealdeer

# --- Hardware & Monitoring ---
openrgb
drm-colortemp
nvtop
power-profiles-daemon
upower

# --- Firewall & Security ---
ufw

#  ---Graphics & Display ---
wl-color-picker

# --- Cosmic ---
cosmic-text-editor
cosmic-files
cosmic-screenshot

# --- Desktop Utilities ---
grim
interception-caps2esc
pavucontrol
profile-sync-daemon
solaar

# --- Audio ---
alsa-firmware
alsa-plugins
alsa-utils
libavutil-52
pipewire-alsa
pipewire-pulse
wireplumber

# --- Development Tools ---
bear
ccache
mold
cmake
conan-bin
cppman
gdb
git
git-delta
git-lfs
imgdiff
just
lazygit
lldb
meld
opencode
resvg
vbindiff

# --- Languages & Runtimes ---
perl
rust
gcc
clang
ninja
nodejs
micromamba-bin
odin
python
python-black
python-defusedxml
python-packaging
python-pylsp-mypy
python-pylsp-rope
python-shtab
python312
uv

# --- LSPs & Formatters ---
just-lsp
wasm-language-tools
bash-language-server
fish-lsp
glsl_analyzer-bin
prettier
pyright
ruff
shfmt
taplo-cli
typescript-language-server
uncrustify
vscode-css-languageserver
vscode-html-languageserver
vscode-json-languageserver
yaml-language-server
odinfmt
ols
marksman

# --- Editors & IDEs ---
helix
vim

# --- Multimedia ---
# davinci-resolve
librsvg
poppler-glib
ffmpegthumbnailer
gst-plugin-pipewire
flameshot
handbrake
krita
mpv
obs-studio
snapshot
imagemagick
ytsurf
ncspot

# File Management
yazi

# Documents & Viewers
presenterm
zathura

# Printing & Scanning
simple-scan

# Gaming
steam
proton-cachyos-slr

# AI & ML

# Web Browsers
google-chrome
zen-browser-bin

# Productivity & Communication
bitwarden
copyq
localsend-bin
worktrunk-bin

# Web Servers & Containers
docker
docker-buildx
docker-compose

# Fonts
ttf-victor-mono-nerd
noto-color-emoji-fontconfig
noto-fonts
noto-fonts-cjk
noto-fonts-emoji
ttf-bitstream-vera
ttf-dejavu
ttf-liberation
ttf-opensans

# Package Management
flatpak
packagekit
paru

# CachyOS — Config & Themes
# cachyos-hello
# cachyos-plymouth-theme
# cachyos-kernel-manager
# cachyos-packageinstaller

# DevOps
aws-cli-bin
granted-bin

# Networking
tailscale
hostess

# Misc
### balena-etcher

