adobe-source-han-sans-cn-fonts
adobe-source-han-sans-jp-fonts
adobe-source-han-sans-kr-fonts
asar
awesome-terminal-fonts
bash-completion
bind
bluez-hid2hci
boost
bpftune-git
btop
cachyos-fish-config
cachyos-gaming-applications
cachyos-gaming-meta
cachyos-micro-settings
cachyos-wallpapers
cachyos-zsh-config
clamav
cosmic-terminal
cosmic-wallpapers
cpupower
dhclient
dmidecode
dmraid
dnsmasq
dosbox
efitools
ethtool
ex-vi-compat
f3d
firefox
freeimage
fsarchiver
fselect-bin
gitui
goverlay
gst-libav
gst-plugins-bad
gst-plugins-ugly
hdparm
help2man
hwdetect
inetutils
inter-font
iwd
jfsutils
libconfig
libdvdcss
libgsf
libopenraw
libwnck3
logiops
lsscsi
ly
mangohud
micro
modemmanager
mtools
nano
nano-syntax-highlighting
nasm
neovim
netctl
networkmanager-openvpn
nfs-utils
nilfs-utils
notion-app-electron
nss-mdns
obsidian
octopi
oh-my-zsh-git
opencascade
opendesktop-fonts
phonon-qt6
phonon-qt6-vlc
powertop
proton-cachyos
proton-cachyos-native
protontricks
python310
python-matplotlib
redshift
sg3_utils
slack-desktop
smartmontools
s-nail
steam-native-runtime
sysfsutils
teamviewer
tigervnc
ttf-meslo-nerd
umu-launcher
usb_modeswitch
visual-studio-code-bin
vtk
wine-cachyos
wine-cachyos-opt
winetricks
wlsunset
xclip
xfsprogs
xl2tpd
xorg-server
xorg-xdpyinfo
xorg-xinit
xorg-xinput
xorg-xkill
zsh-autosuggestions
zsh-history-substring-search
zsh-syntax-highlighting
