# Packages marked as discarded in pacman_install.conf but still installed
cachyos-gaming-applications
cachyos-gaming-meta
wine-cachyos
wine-cachyos-opt
proton-cachyos-slr
protontricks
winetricks
umu-launcher
dosbox
help2man
logiops
libconfig
nasm
goverlay
cachyos-micro-settings
mangohud
steam-native-runtime
obsidian
notion-app-electron
slack-desktop
teamviewer
firefox
oh-my-zsh-git
zsh-autosuggestions
zsh-history-substring-search
zsh-syntax-highlighting
redshift
wlsunset

# Remove these packages to clean up the system
adobe-source-han-sans-cn-fonts
adobe-source-han-sans-jp-fonts
adobe-source-han-sans-kr-fonts
asar
awesome-terminal-fonts
bash-completion
bind
bluez-hid2hci
boost
bpftune-git
btop
cachyos-wallpapers
cosmic-terminal
cosmic-wallpapers
cpupower
dhclient
dmidecode
dmraid
dnsmasq
efitools
ethtool
ex-vi-compat
f3d
fsarchiver
fselect-bin
gitui
gst-plugins-bad
gst-plugins-ugly
hdparm
hwdetect
inetutils
inter-font
iwd
jfsutils
libdvdcss
libgsf
libwnck3
lsscsi
ly
micro
modemmanager
mtools
nano
nano-syntax-highlighting
neovim
netctl
networkmanager-openvpn
nfs-utils
nilfs-utils
nss-mdns
octopi
opendesktop-fonts
powertop
python-matplotlib
sg3_utils
smartmontools
s-nail
sysfsutils
ttf-meslo-nerd
usb_modeswitch
visual-studio-code-bin
xclip
xfsprogs
xl2tpd
xorg-xdpyinfo
xorg-xkill
