
inherits = "catppuccin_mocha"
"comment" = { fg = "surface2", bg = "mantle" }
"ui.virtual.inlay-hint" = { fg = "surface1" }

# inherits = "gruvbox_dark_hard"
# "string" = { fg = "purple1", modifiers = ["italic"]}
# "string" = { bg = "#914266", modifiers = ["italic"]}
# "comment" = { bg = "gray" }

# inherits = "gruvbox-material"
# inherits = "adwaita-dark"
# inherits = "catppuccin_mocha"
# inherits = "nordic"

# inherits = "yellowed"
# "ui.virtual.ruler" = { bg = "#2A2A2A" }

# inherits = "wolf-alabaster-dark"
# "ui.gutter" = {}
# "ui.bufferline.background" = { }
# "ui.bufferline" = { fg = "#2A2A2A" }
# "ui.cursorline" = { bg = "#2A2A2A" }
# "ui.cursorcolumn" = { bg = "#2A2A2A" }

"ui.background" = {}
# "comment" = { fg = "#2299DD" }
"ui.virtual.jump-label" = { fg = "black", bg = "yellow", modifiers = ["bold"] }
